### ISSUE TITLE
Can't build on Ubuntu 18.04

### ISSUE THREAD

**Issue by stephendliang** [vertcoin-project/vertcoin-core#43]
I cannot build properly on my Ubuntu 18.04 VPS, and encounter the following error:

```
CXX      libbitcoin_server_a-pow.o
In file included from pow.cpp:10:0:
./bignum.h:57:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/bn.h:32:0,
                 from ./bignum.h:17,
                 from pow.cpp:10:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from pow.cpp:10:0:
./bignum.h: In constructor ‘CBigNum::CBigNum()’:
./bignum.h:62:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
./bignum.h:62:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
./bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
./bignum.h:67:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
./bignum.h:67:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
./bignum.h:68:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
./bignum.h:70:31: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
             BN_clear_free(this);
                               ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator=(const CBigNum&)’:
./bignum.h:77:30: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘BIGNUM* BN_copy(BIGNUM*, const BIGNUM*)’
         if (!BN_copy(this, &b))
                              ^
./bignum.h: In destructor ‘CBigNum::~CBigNum()’:
./bignum.h:84:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_clear_free(BIGNUM*)’
         BN_clear_free(this);
                           ^
./bignum.h: In constructor ‘CBigNum::CBigNum(signed char)’:
./bignum.h:88:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(signed char n)        { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
./bignum.h:88:37: note: suggested alternative: ‘BN_print’
     CBigNum(signed char n)        { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(short int)’:
./bignum.h:89:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(short n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
./bignum.h:89:37: note: suggested alternative: ‘BN_print’
     CBigNum(short n)              { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(int)’:
./bignum.h:90:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(int n)                { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
./bignum.h:90:37: note: suggested alternative: ‘BN_print’
     CBigNum(int n)                { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(long int)’:
./bignum.h:91:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(long n)               { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
./bignum.h:91:37: note: suggested alternative: ‘BN_print’
     CBigNum(long n)               { BN_init(this); if (n >= 0) setulong(n); else setint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(long long int)’:
./bignum.h:92:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(long long n)          { BN_init(this); setint64(n); }
                                     ^~~~~~~
./bignum.h:92:37: note: suggested alternative: ‘BN_print’
     CBigNum(long long n)          { BN_init(this); setint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(unsigned char)’:
./bignum.h:93:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned char n)      { BN_init(this); setulong(n); }
                                     ^~~~~~~
./bignum.h:93:37: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned char n)      { BN_init(this); setulong(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(short unsigned int)’:
./bignum.h:94:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned short n)     { BN_init(this); setulong(n); }
                                     ^~~~~~~
./bignum.h:94:37: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned short n)     { BN_init(this); setulong(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(unsigned int)’:
./bignum.h:95:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned int n)       { BN_init(this); setulong(n); }
                                     ^~~~~~~
./bignum.h:95:37: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned int n)       { BN_init(this); setulong(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(long unsigned int)’:
./bignum.h:96:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned long n)      { BN_init(this); setulong(n); }
                                     ^~~~~~~
./bignum.h:96:37: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned long n)      { BN_init(this); setulong(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(long long unsigned int)’:
./bignum.h:97:37: error: ‘BN_init’ was not declared in this scope
     CBigNum(unsigned long long n) { BN_init(this); setuint64(n); }
                                     ^~~~~~~
./bignum.h:97:37: note: suggested alternative: ‘BN_print’
     CBigNum(unsigned long long n) { BN_init(this); setuint64(n); }
                                     ^~~~~~~
                                     BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(uint256_old)’:
./bignum.h:98:41: error: ‘BN_init’ was not declared in this scope
     explicit CBigNum(uint256_old n)   { BN_init(this); setuint256(n); }
                                         ^~~~~~~
./bignum.h:98:41: note: suggested alternative: ‘BN_print’
     explicit CBigNum(uint256_old n)   { BN_init(this); setuint256(n); }
                                         ^~~~~~~
                                         BN_print
./bignum.h: In constructor ‘CBigNum::CBigNum(const std::vector<unsigned char>&)’:
./bignum.h:102:9: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
         ^~~~~~~
./bignum.h:102:9: note: suggested alternative: ‘BN_print’
         BN_init(this);
         ^~~~~~~
         BN_print
./bignum.h: In member function ‘void CBigNum::setulong(long unsigned int)’:
./bignum.h:108:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_set_word(BIGNUM*, long unsigned int)’
         if (!BN_set_word(this, n))
                                 ^
./bignum.h: In member function ‘long unsigned int CBigNum::getulong() const’:
./bignum.h:114:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
         return BN_get_word(this);
                                ^
./bignum.h: In member function ‘unsigned int CBigNum::getuint() const’:
./bignum.h:119:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
         return BN_get_word(this);
                                ^
./bignum.h: In member function ‘int CBigNum::getint() const’:
./bignum.h:124:43: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
         unsigned long n = BN_get_word(this);
                                           ^
./bignum.h:125:33: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
         if (!BN_is_negative(this))
                                 ^
In file included from pow.cpp:10:0:
./bignum.h: In member function ‘void CBigNum::setint64(int64_t)’:
./bignum.h:173:37: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, p - pch, this);
                                     ^
./bignum.h: In member function ‘void CBigNum::setuint64(uint64_t)’:
./bignum.h:200:37: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, p - pch, this);
                                     ^
./bignum.h: In member function ‘void CBigNum::setuint256(uint256_old)’:
./bignum.h:228:37: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(pch, p - pch, this);
                                     ^
./bignum.h: In member function ‘uint256_old CBigNum::getuint256() const’:
./bignum.h:233:50: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         unsigned int nSize = BN_bn2mpi(this, NULL);
                                                  ^
./bignum.h:238:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
./bignum.h: In member function ‘void CBigNum::setvch(const std::vector<unsigned char>&)’:
./bignum.h:258:46: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘3’ to ‘BIGNUM* BN_mpi2bn(const unsigned char*, int, BIGNUM*)’
         BN_mpi2bn(&vch2[0], vch2.size(), this);
                                              ^
./bignum.h: In member function ‘std::vector<unsigned char> CBigNum::getvch() const’:
./bignum.h:263:50: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         unsigned int nSize = BN_bn2mpi(this, NULL);
                                                  ^
./bignum.h:267:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_bn2mpi(const BIGNUM*, unsigned char*)’
         BN_bn2mpi(this, &vch[0]);
                                ^
./bignum.h: In member function ‘CBigNum& CBigNum::SetCompact(unsigned int)’:
./bignum.h:303:36: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_set_word(BIGNUM*, long unsigned int)’
             BN_set_word(this, nWord);
                                    ^
./bignum.h:307:36: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_set_word(BIGNUM*, long unsigned int)’
             BN_set_word(this, nWord);
                                    ^
./bignum.h:308:46: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_lshift(BIGNUM*, const BIGNUM*, int)’
             BN_lshift(this, this, 8*(nSize-3));
                                              ^
./bignum.h:310:40: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_set_negative(BIGNUM*, int)’
         BN_set_negative(this, fNegative);
                                        ^
In file included from ./bignum.h:17:0,
                 from pow.cpp:10:
./bignum.h: In member function ‘unsigned int CBigNum::GetCompact() const’:
./bignum.h:316:30: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_num_bits(const BIGNUM*)’
         unsigned int nSize = BN_num_bytes(this);
                              ^
In file included from pow.cpp:10:0:
./bignum.h:319:40: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
             nCompact = BN_get_word(this) << 8*(3-nSize);
                                        ^
./bignum.h:323:45: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_rshift(BIGNUM*, const BIGNUM*, int)’
             BN_rshift(&bn, this, 8*(nSize-3));
                                             ^
./bignum.h:324:39: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘long unsigned int BN_get_word(const BIGNUM*)’
             nCompact = BN_get_word(&bn);
                                       ^
./bignum.h:334:41: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
         nCompact |= (BN_is_negative(this) ? 0x00800000 : 0);
                                         ^
./bignum.h: In member function ‘std::__cxx11::string CBigNum::ToString(int) const’:
./bignum.h:375:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘void BN_set_negative(BIGNUM*, int)’
         BN_set_negative(&bn, false);
                                   ^
./bignum.h:378:29: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         if (BN_cmp(&bn, &bn0) == 0)
                             ^
./bignum.h:380:32: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         while (BN_cmp(&bn, &bn0) > 0)
                                ^
./bignum.h:382:54: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
             if (!BN_div(&dv, &rem, &bn, &bnBase, pctx))
                                                      ^
./bignum.h:388:32: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
         if (BN_is_negative(this))
                                ^
./bignum.h: In member function ‘bool CBigNum::operator!() const’:
./bignum.h:421:31: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_zero(const BIGNUM*)’
         return BN_is_zero(this);
                               ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator+=(const CBigNum&)’:
./bignum.h:426:35: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_add(this, this, &b))
                                   ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator*=(const CBigNum&)’:
./bignum.h:440:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
         if (!BN_mul(this, this, &b, pctx))
                                         ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator<<=(unsigned int)’:
./bignum.h:459:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_lshift(BIGNUM*, const BIGNUM*, int)’
         if (!BN_lshift(this, this, shift))
                                         ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator>>=(unsigned int)’:
./bignum.h:470:28: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
         if (BN_cmp(&a, this) > 0)
                            ^
./bignum.h:476:41: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_rshift(BIGNUM*, const BIGNUM*, int)’
         if (!BN_rshift(this, this, shift))
                                         ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator++()’:
./bignum.h:485:47: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_add(this, this, BN_value_one()))
                                               ^
./bignum.h: In member function ‘CBigNum& CBigNum::operator--()’:
./bignum.h:502:45: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)’
         if (!BN_sub(&r, this, BN_value_one()))
                                             ^
./bignum.h: In function ‘const CBigNum operator+(const CBigNum&, const CBigNum&)’:
./bignum.h:527:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_add(BIGNUM*, const BIGNUM*, const BIGNUM*)’
     if (!BN_add(&r, &a,bitcoind, v &b))
                           ^
./bignum.h: In function ‘const CBigNum operator-(const CBigNum&, const CBigNum&)’:
./bignum.h:535:27: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_sub(BIGNUM*, const BIGNUM*, const BIGNUM*)’
     if (!BN_sub(&r, &a, &b))
                           ^
./bignum.h: In function ‘const CBigNum operator-(const CBigNum&)’:
./bignum.h:543:43: error: cannot convert ‘CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_is_negative(const BIGNUM*)’
     BN_set_negative(&r, !BN_is_negative(&r));
                                           ^
./bignum.h: In function ‘const CBigNum operator*(const CBigNum&, const CBigNum&)’:
./bignum.h:551:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_mul(BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_mul(&r, &a, &b, pctx))
                                 ^
./bignum.h: In function ‘const CBigNum operator/(const CBigNum&, const CBigNum&)’:
./bignum.h:560:39: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_div(&r, NULL, &a, &b, pctx))
                                       ^
In file included from ./bignum.h:17:0,
                 from pow.cpp:10:
./bignum.h: In function ‘const CBigNum operator%(const CBigNum&, const CBigNum&)’:
./bignum.h:569:10: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘2’ to ‘int BN_div(BIGNUM*, BIGNUM*, const BIGNUM*, const BIGNUM*, BN_CTX*)’
     if (!BN_mod(&r, &a, &b, pctx))
          ^
In file included from pow.cpp:10:0:
./bignum.h: In function ‘const CBigNum operator<<(const CBigNum&, unsigned int)’:
./bignum.h:577:33: error: cannot convert ‘CBigNum*’ to ‘BIGNUM* {aka bignum_st*}’ for argument ‘1’ to ‘int BN_lshift(BIGNUM*, const BIGNUM*, int)’
     if (!BN_lshift(&r, &a, shift))
                                 ^
./bignum.h: In function ‘bool operator==(const CBigNum&, const CBigNum&)’:
./bignum.h:589:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator==(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) == 0); }
                                                                                   ^
./bignum.h: In function ‘bool operator!=(const CBigNum&, const CBigNum&)’:
./bignum.h:590:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator!=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) != 0); }
                                                                                   ^
./bignum.h: In function ‘bool operator<=(const CBigNum&, const CBigNum&)’:
./bignum.h:591:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator<=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) <= 0); }
                                                                                   ^
./bignum.h: In function ‘bool operator>=(const CBigNum&, const CBigNum&)’:
./bignum.h:592:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator>=(const CBigNum& a, const CBigNum& b) { return (BN_cmp(&a, &b) >= 0); }
                                                                                   ^
./bignum.h: In function ‘bool operator<(const CBigNum&, const CBigNum&)’:
./bignum.h:593:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator<(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) < 0); }
                                                                                   ^
./bignum.h: In function ‘bool operator>(const CBigNum&, const CBigNum&)’:
./bignum.h:594:83: error: cannot convert ‘const CBigNum*’ to ‘const BIGNUM* {aka const bignum_st*}’ for argument ‘1’ to ‘int BN_cmp(const BIGNUM*, const BIGNUM*)’
 inline bool operator>(const CBigNum& a, const CBigNum& b)  { return (BN_cmp(&a, &b) > 0); }
                                                                                   ^
Makefile:6135: recipe for target 'libbitcoin_server_a-pow.o' failed
```

I built it vanilla:

```
./autogen.sh
./configure
make
```

I've already looked into this problem fairly well, and have found out that you will need to downgrade OpenSSL (I need 1.0.1, but I have 1.1.0) as stated here: https://github.com/stratisproject/stratisX/issues/33, and here https://garanto.org/vertcoin-project-vertcoin-core-error-with-bignum-h-during-make-39-2.html and here https://github.com/thegreatoldone/skidoo/issues/6.

However, I have already installed bitcoind, litecoind, and zcoind on this VPS (also built from source), and those depend on this recent version of OpenSSL 1.1.0.

How can I manage this situation? Can I install multiple versions of OpenSSL on the same system if they are conflicting?

**Comment by ghost** [comment]
[This thread](https://serverfault.com/a/305514) may help with regard to installing multiple versions of OpenSSL.

**Comment by stephendliang** [comment]
I tried to change all instances of libssl in the makefile to libssl1.0.0, and the same error occurred

**Comment by metalicjames** [comment]
Fixed in 5522e0ce9

**Comment by TTcoinDeveloper** [comment]
wget http://www.openssl.org/source/openssl-1.0.2a.tar.gz
tar -xvzf openssl-1.0.2a.tar.gz
cd openssl-1.0.2a
./config --prefix=/usr/   
make
sudo make install
