### ISSUE TITLE
Can not make windows build on ubuntu 14.04

### ISSUE THREAD

**Issue by fujicoin** [vertcoin-project/vertcoin-core#26]
I built it on ubuntu 14.04 with the following procedure.
```
apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
apt-get install g++-mingw-w64-x86-64 mingw-w64-x86-64-dev
git clone https://github.com/vertcoin/vertcoin.git
cd vertcoin/depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make
```
Then the following error occurs in the last `make`.
```
Making all in src
make[1]: Entering directory `/root/deps/vertcoin/src'
make[2]: Entering directory `/root/deps/vertcoin/src'
make[3]: Entering directory `/root/deps/vertcoin'
make[3]: Leaving directory `/root/deps/vertcoin'
make[3]: Entering directory `/root/deps/vertcoin/src/secp256k1'
make[3]: Leaving directory `/root/deps/vertcoin/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
crypto/.libs/libbitcoinconsensus_la-scrypt.o:scrypt.cpp:(.text.startup+0x13): undefined reference to `boost::system::generic_category()'
crypto/.libs/libbitcoinconsensus_la-scrypt.o:scrypt.cpp:(.text.startup+0x1f): undefined reference to `boost::system::generic_category()'
/usr/bin/x86_64-w64-mingw32-ld: crypto/.libs/libbitcoinconsensus_la-scrypt.o: bad reloc address 0x1f in section `.text.startup'
collect2: error: ld returned 1 exit status
make[2]: *** [libbitcoinconsensus.la] Error 1
make[2]: Leaving directory `/root/deps/vertcoin/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/deps/vertcoin/src'
make: *** [all-recursive] Error 1
```
It seems necessary to specify the library - lboost_system to be linked when scrypt.cpp is compiled.
Where should I fix it?

**Comment by metalicjames** [comment]
I use Docker to produce the Vertcoin Core builds for Windows.

Dockerfile:
```
FROM ubuntu:14.04
MAINTAINER James Lovejoy <jameslovejoy1@gmail.com>

# Make sure the package repository is up to date.
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git python-software-properties software-properties-common

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential python3 openjdk-8-jre-headless curl autoconf automake libtool pkg-config bsdmainutils cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev python3 nsis g++-mingw-w64-x86-64 wine1.6 bc g++-arm-linux-gnueabihf python-pip

RUN pip install ez_setup
```

Build:
```
export WORKSPACE=/home/james/workspace
git clone https://github.com/vertcoin/vertcoin.git && cd vertcoin
export HOST=x86_64-w64-mingw32
make -C depends HOST=$HOST
mkdir -p $WORKSPACE/out/$HOST
mkdir build && cd build
../configure --disable-dependency-tracking --disable-tests --disable-bench --prefix=$WORKSPACE/depends/$HOST --enable-reduce-exports --bindir=$WORKSPACE/out/$HOST/bin --libdir=$WORKSPACE/out/$HOST/lib --disable-shared
make install
cd ../
rm -rf build
```

**Comment by fujicoin** [comment]
Thank you for answering.
But,
Do not run `. / autogen.sh`?
If you do not do that, `configure` will not be created.
next
`../configure --disable - dependency - tracking --disable - tests --disable - bench --prefix = $ WORKSPACE / depends / $ HOST --enable - reduce - exports --bindir = $ WORKSPACE / out / $ HOST / bin - libdir = $ WORKSPACE / out / $ HOST / lib - disable - shared `
The result is shown below.
```
Options used to compile and link:
  with wallet   = yes
  with gui / qt = no
  with zmq      = no
  with test     = no
  with bench    = no
  with upnp     = auto
  use asm       = yes
  debug enabled = no
  werror        = no

  target os     = linux
  build os      = 

  CC            = gcc
  CFLAGS        = -g -O2 -fPIC
  CPPFLAGS      =  -DHAVE_BUILD_INFO -D__STDC_FORMAT_MACROS
  CXX           = g++ -std=c++11
  CXXFLAGS      = -g -O2 -Wall -Wextra -Wformat -Wvla -Wformat-security -Wno-unused-parameter -fvisibility=hidden
  LDFLAGS       = 
  ARFLAGS       = cr
```
This makes it impossible to create QT for windows.
Please tell me the correct procedure.

**Comment by fujicoin** [comment]
Because you gave me a hint, I was able to compile the windows wallet.
I used Ubntu 14.04 on VMware.
I thank you very much.

**Comment by fujicoin** [comment]
By the way, I have a question.
Is makeseeds.py and generate-seeds.py running during compilation?

**Comment by denarii-coin** [comment]
If the directions dont work, why leave them up? @metalicjames
